-- GENERATED by Limer's designer from design/login.design.lua.
-- Regenerate from the designer; edits here are overwritten.
local ui = require("limekit.ui")

local M = {}

M.root = ui.Container()
M.name = ui.LineEdit()
M.name:setHint("Your name")
M.password = ui.LineEdit()
M.password:setHint("Password")
M.password:setInputMode("password")
M.buttons = ui.Container()
M.cancel = ui.Button()
M.cancel:setText("Cancel")
M.ok = ui.Button()
M.ok:setText("OK")
M.status = ui.Label()
M.status:setText("")

local buttonsLayout = ui.HLayout()
buttonsLayout:addStretch(1)
buttonsLayout:addChild(M.cancel)
buttonsLayout:addChild(M.ok)
M.buttons:setLayout(buttonsLayout)

local rootLayout = ui.FormLayout()
rootLayout:addChild("Name", M.name)
rootLayout:addChild("Password", M.password)
rootLayout:addChild("", M.buttons)
rootLayout:addChild("", M.status)
M.root:setLayout(rootLayout)

M.window = ui.Window { title = "Login" }
M.window:setSize(360, 200)
M.window:setMainChild(M.root)

return M
